"""Validate graph-owned road-aware forest clear/refill behavior.

This fixture proves the production target before touching ecosystem graph
families: forest points are generated by a PCG graph, a runtime road spline is
read as PCG data, and moving the road spline clears the new corridor while
allowing the previous corridor to refill on regeneration.
"""

import json
import math
import os
import time

import unreal


REPORT_NAME = "CubelessRoadAwareForestClearRefill_Report.json"
STATE_ATTR = "_cubeless_road_aware_forest_clear_refill_state"

GRAPH_FOLDER = "/Game/_MCP_Temp/PCG/Graphs"
GRAPH_NAME = "PCG_Cubeless_RoadAwareForestClearRefill_MCP"
GRAPH_OBJECT = GRAPH_FOLDER + "/" + GRAPH_NAME + "." + GRAPH_NAME

ROAD_BP_CLASS_PATH = (
    "/Game/Cubeless/PCG/Runtime/Blueprints/"
    "BP_Cubeless_PCG_ForestRoadRuntime.BP_Cubeless_PCG_ForestRoadRuntime_C"
)

ROAD_ACTOR_LABEL = "MCP_RoadAwareForestClearRefill_RoadSource"
PCG_VOLUME_LABEL = "MCP_RoadAwareForestClearRefill_PCGVolume"
ROAD_ACTOR_TAG = "MCPRoadAwareForestSource"
ROAD_SPLINE_TAG = "MCPRoadAwareForestSpline"

GRID_ORIGIN = unreal.Vector(0.0, 0.0, 0.0)
GRID_EXTENTS = unreal.Vector(4500.0, 3500.0, 50.0)
GRID_CELL_SIZE = unreal.Vector(500.0, 500.0, 100.0)
ROAD_CLEARANCE_CM = 650.0
ROAD_FILTER_EXTRA_CLEARANCE_CM = 80.0
WAIT_SECONDS = 5.0

CUBE_MESH = "/Engine/BasicShapes/Cube.Cube"


def _all_level_actors():
    subsystem_cls = getattr(unreal, "EditorActorSubsystem", None)
    if subsystem_cls:
        subsystem = unreal.get_editor_subsystem(subsystem_cls)
        if subsystem:
            return list(subsystem.get_all_level_actors())
    return list(unreal.EditorLevelLibrary.get_all_level_actors())


def _actor_label(actor):
    try:
        return actor.get_actor_label()
    except Exception:
        return actor.get_name()


def _find_actor(label):
    for actor in _all_level_actors():
        if _actor_label(actor) == label:
            return actor
    return None


def _make_rotator(pitch=0.0, yaw=0.0, roll=0.0):
    rotator = unreal.Rotator()
    rotator.pitch = float(pitch)
    rotator.yaw = float(yaw)
    rotator.roll = float(roll)
    return rotator


def _load_asset(path):
    asset = unreal.EditorAssetLibrary.load_asset(path)
    if not asset:
        asset = unreal.load_object(None, path)
    return asset


def _report_path():
    out_dir = os.path.join(unreal.Paths.project_saved_dir(), "MCP_RoadPCG")
    os.makedirs(out_dir, exist_ok=True)
    return os.path.join(out_dir, REPORT_NAME)


def _write_report(report):
    path = _report_path()
    report["report_path"] = path
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, ensure_ascii=False)
    unreal.log("Cubeless road-aware forest clear/refill report: {}".format(path))
    print(json.dumps(report, ensure_ascii=False))
    return path


def _selector(attribute_name, selector_cls):
    selector = selector_cls()
    selector.import_text('(AttributeName="{}")'.format(attribute_name))
    return selector


def _constant(metadata_type, value):
    constant = unreal.PCGMetadataTypesConstantStruct()
    constant.set_editor_property("type", metadata_type)
    if metadata_type == unreal.PCGMetadataTypes.DOUBLE:
        constant.set_editor_property("double_value", float(value))
    elif metadata_type == unreal.PCGMetadataTypes.FLOAT:
        constant.set_editor_property("float_value", float(value))
    elif metadata_type == unreal.PCGMetadataTypes.INTEGER32:
        constant.set_editor_property("int32_value", int(value))
    elif metadata_type == unreal.PCGMetadataTypes.BOOLEAN:
        constant.set_editor_property("bool_value", bool(value))
    else:
        raise ValueError("Unsupported constant type: {}".format(metadata_type))
    return constant


def _pin_label(pin):
    try:
        return str(pin.get_editor_property("properties").get_editor_property("label"))
    except Exception:
        try:
            return pin.get_name()
        except Exception:
            return str(pin)


def _add_node(graph, settings_cls, title, x, y):
    created = graph.add_node_of_type(settings_cls.static_class())
    node = created[0] if isinstance(created, tuple) else created
    try:
        node.set_editor_property("node_title", title)
    except Exception:
        try:
            node.node_title = title
        except Exception:
            pass
    try:
        node.set_node_position(int(x), int(y))
    except Exception:
        pass
    return node


def _add_edge(graph, from_node, to_node, from_pin="Out", to_pin="In"):
    try:
        graph.add_edge(from_node, unreal.Name(from_pin), to_node, unreal.Name(to_pin))
        return {
            "from": from_node.get_name(),
            "from_pin": from_pin,
            "to": to_node.get_name(),
            "to_pin": to_pin,
            "ok": True,
        }
    except Exception as exc:
        return {
            "from": from_node.get_name(),
            "from_pin": from_pin,
            "to": to_node.get_name(),
            "to_pin": to_pin,
            "ok": False,
            "error": str(exc),
        }


def _node_summary(node):
    try:
        settings_class = node.get_settings().get_class().get_name()
    except Exception:
        settings_class = ""
    try:
        title = str(node.get_editor_property("node_title"))
    except Exception:
        title = str(getattr(node, "node_title", ""))
    return {
        "node": node.get_name(),
        "title": title,
        "settings_class": settings_class,
        "input_pins": [
            {"label": _pin_label(pin), "connected": bool(pin.is_connected())}
            for pin in getattr(node, "input_pins", [])
        ],
        "output_pins": [
            {"label": _pin_label(pin), "connected": bool(pin.is_connected())}
            for pin in getattr(node, "output_pins", [])
        ],
    }


def _weighted_mesh_entry(mesh_path):
    entry = unreal.PCGMeshSelectorWeightedEntry()
    text = entry.export_text()
    text = text.replace("StaticMesh=None", 'StaticMesh="{}"'.format(mesh_path))
    entry.import_text(text)
    try:
        entry.set_editor_property("weight", 1)
    except Exception:
        pass
    return entry


def _configure_grid(node):
    settings = node.get_settings()
    settings.set_editor_property("grid_extents", GRID_EXTENTS)
    settings.set_editor_property("cell_size", GRID_CELL_SIZE)
    settings.set_editor_property("set_points_bounds", True)
    settings.set_editor_property("cull_points_outside_volume", False)
    try:
        settings.set_editor_property("point_position", unreal.PCGPointPosition.CELL_CENTER)
    except Exception:
        pass
    try:
        settings.set_editor_property("seed", 6102026)
    except Exception:
        pass


def _configure_get_road_spline(node):
    settings = node.get_settings()
    actor_selector = settings.get_editor_property("actor_selector")
    actor_selector.set_editor_property("actor_filter", unreal.PCGActorFilter.ALL_WORLD_ACTORS)
    actor_selector.set_editor_property("actor_selection", unreal.PCGActorSelection.BY_TAG)
    actor_selector.set_editor_property("actor_selection_tag", ROAD_ACTOR_TAG)
    actor_selector.set_editor_property("select_multiple", False)
    actor_selector.set_editor_property("ignore_self_and_children", False)
    settings.set_editor_property("actor_selector", actor_selector)

    component_selector = settings.get_editor_property("component_selector")
    component_selector.set_editor_property("component_selection", unreal.PCGComponentSelection.BY_TAG)
    component_selector.set_editor_property("component_selection_tag", ROAD_SPLINE_TAG)
    settings.set_editor_property("component_selector", component_selector)
    settings.set_editor_property("always_requery_actors", True)
    settings.set_editor_property("components_must_overlap_self", False)
    settings.set_editor_property("track_actors_only_within_bounds", False)


def _configure_spline_sampler(node):
    settings = node.get_settings()
    params = settings.get_editor_property("sampler_params")
    params.set_editor_property("dimension", unreal.PCGSplineSamplingDimension.ON_SPLINE)
    params.set_editor_property("mode", unreal.PCGSplineSamplingMode.DISTANCE)
    params.set_editor_property("distance_increment", 120.0)
    params.set_editor_property("subdivisions_per_segment", 8)
    params.set_editor_property("compute_distance", True)
    params.set_editor_property("compute_segment_index", True)
    settings.set_editor_property("sampler_params", params)


def _configure_distance(node):
    settings = node.get_settings()
    settings.set_editor_property("output_to_attribute", True)
    settings.set_editor_property(
        "output_attribute",
        _selector("RoadClearanceDistance", unreal.PCGAttributePropertySelector),
    )
    settings.set_editor_property("maximum_distance", ROAD_CLEARANCE_CM * 3.0)
    settings.set_editor_property("set_density", False)
    settings.set_editor_property("source_shape", unreal.PCGDistanceShape.CENTER)
    settings.set_editor_property("target_shape", unreal.PCGDistanceShape.CENTER)


def _configure_clearance_filter(node):
    settings = node.get_settings()
    settings.set_editor_property(
        "target_attribute",
        _selector("RoadClearanceDistance", unreal.PCGAttributePropertyInputSelector),
    )
    settings.set_editor_property("operator", unreal.PCGAttributeFilterOperator.GREATER_OR_EQUAL)
    settings.set_editor_property("use_constant_threshold", True)
    settings.set_editor_property(
        "attribute_types",
        _constant(unreal.PCGMetadataTypes.DOUBLE, ROAD_CLEARANCE_CM + ROAD_FILTER_EXTRA_CLEARANCE_CM),
    )
    settings.set_editor_property("generate_output_data_even_if_empty", True)
    try:
        settings.set_editor_property("warn_on_data_missing_attribute", False)
    except Exception:
        pass


def _configure_spawner(node):
    settings = node.get_settings()
    settings.set_mesh_selector_type(unreal.PCGMeshSelectorWeighted)
    selector = settings.get_editor_property("mesh_selector_parameters")
    entries = selector.get_editor_property("mesh_entries")
    entries.clear()
    entries.append(_weighted_mesh_entry(CUBE_MESH))
    selector.set_editor_property("mesh_entries", entries)
    try:
        settings.set_editor_property("synchronous_load", True)
        settings.set_editor_property("apply_mesh_bounds_to_points", True)
    except Exception:
        pass


def _create_or_update_graph():
    if not unreal.EditorAssetLibrary.does_directory_exist(GRAPH_FOLDER):
        unreal.EditorAssetLibrary.make_directory(GRAPH_FOLDER)
    graph = unreal.load_object(None, GRAPH_OBJECT)
    created = False
    if not graph:
        factory = unreal.PCGGraphFactory()
        graph = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            GRAPH_NAME,
            GRAPH_FOLDER,
            unreal.PCGGraph,
            factory,
        )
        created = bool(graph)
    if not graph:
        raise RuntimeError("Failed to create/load graph: " + GRAPH_OBJECT)

    for node in list(graph.nodes):
        try:
            graph.remove_node(node)
        except Exception:
            pass

    nodes = {
        "grid": _add_node(graph, unreal.PCGCreatePointsGridSettings, "Create Deterministic Forest Point Grid", 0, 0),
        "get_road": _add_node(graph, unreal.PCGGetSplineSettings, "Get Runtime Road Spline", 0, -300),
        "road_reference_points": _add_node(graph, unreal.PCGSplineSamplerSettings, "Sample Road Clearance Reference Points", 360, -300),
        "distance": _add_node(graph, unreal.PCGDistanceSettings, "Compute RoadClearanceDistance", 360, 0),
        "filter": _add_node(graph, unreal.PCGAttributeFilteringSettings, "Keep Points Outside Road Clearance", 720, 0),
        "spawn": _add_node(graph, unreal.PCGStaticMeshSpawnerSettings, "Spawn Road-Aware Forest Cubes", 1080, 0),
    }
    _configure_grid(nodes["grid"])
    _configure_get_road_spline(nodes["get_road"])
    _configure_spline_sampler(nodes["road_reference_points"])
    _configure_distance(nodes["distance"])
    _configure_clearance_filter(nodes["filter"])
    _configure_spawner(nodes["spawn"])

    edges = [
        _add_edge(graph, nodes["grid"], nodes["distance"], "Out", "Source"),
        _add_edge(graph, nodes["get_road"], nodes["road_reference_points"], "Out", "Spline"),
        _add_edge(graph, nodes["road_reference_points"], nodes["distance"], "Out", "Target"),
        _add_edge(graph, nodes["distance"], nodes["filter"], "Out", "In"),
        _add_edge(graph, nodes["filter"], nodes["spawn"], "InsideFilter", "In"),
        _add_edge(graph, nodes["spawn"], graph.get_output_node(), "Out", "Out"),
    ]

    try:
        graph.description = (
            "Temporary validation graph for road-aware forest clear/refill. "
            "A grid of forest points is filtered by distance to reference points sampled "
            "from a tagged runtime road spline before StaticMeshSpawner output."
        )
        graph.get_input_node().set_node_position(-260, 0)
        graph.get_output_node().set_node_position(1420, 0)
    except Exception:
        pass
    saved = bool(unreal.EditorAssetLibrary.save_loaded_asset(graph, False))
    return {
        "graph": graph,
        "created": created,
        "saved": saved,
        "road_clearance_cm": ROAD_CLEARANCE_CM,
        "road_filter_extra_clearance_cm": ROAD_FILTER_EXTRA_CLEARANCE_CM,
        "road_reference_point_distance_increment_cm": 120.0,
        "edges": edges,
        "edge_errors": [edge for edge in edges if not edge.get("ok")],
        "nodes": [_node_summary(node) for node in nodes.values()],
    }


def _cleanup_existing_fixture():
    removed = []
    for actor in list(_all_level_actors()):
        if _actor_label(actor) not in {ROAD_ACTOR_LABEL, PCG_VOLUME_LABEL}:
            continue
        label = _actor_label(actor)
        try:
            for component in actor.get_components_by_class(unreal.PCGComponent):
                try:
                    component.cleanup(True)
                except Exception:
                    pass
            unreal.EditorLevelLibrary.destroy_actor(actor)
            removed.append(label)
        except Exception:
            pass
    return removed


def _ensure_road_actor():
    actor_class = unreal.load_object(None, ROAD_BP_CLASS_PATH)
    if not actor_class:
        raise RuntimeError("Missing road runtime Blueprint class: " + ROAD_BP_CLASS_PATH)
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(actor_class, GRID_ORIGIN, _make_rotator())
    if not actor:
        raise RuntimeError("Failed to spawn road source actor.")
    actor.set_actor_label(ROAD_ACTOR_LABEL)
    actor.set_editor_property(
        "tags",
        [unreal.Name(ROAD_ACTOR_TAG), unreal.Name("MCPValidation")],
    )
    spline = _road_spline(actor)
    _tag_spline(spline)
    return actor


def _ensure_pcg_volume(graph):
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.PCGVolume,
        GRID_ORIGIN,
        _make_rotator(),
    )
    if not actor:
        raise RuntimeError("Failed to spawn PCGVolume.")
    actor.set_actor_label(PCG_VOLUME_LABEL)
    actor.set_editor_property("tags", [unreal.Name("MCPValidation")])
    try:
        actor.set_actor_scale3d(unreal.Vector(100.0, 100.0, 20.0))
    except Exception:
        pass
    components = list(actor.get_components_by_class(unreal.PCGComponent))
    if not components:
        raise RuntimeError("PCGVolume has no PCGComponent.")
    component = components[0]
    component.set_graph(graph)
    return actor


def _road_spline(actor):
    splines = list(actor.get_components_by_class(unreal.SplineComponent))
    if not splines:
        raise RuntimeError("Road actor has no SplineComponent.")
    for spline in splines:
        if spline.get_name() == "Road_SourceSpline":
            return spline
    return splines[0]


def _tag_spline(spline):
    try:
        tags = list(spline.get_editor_property("component_tags"))
    except Exception:
        tags = []
    names = {str(tag) for tag in tags}
    if ROAD_SPLINE_TAG not in names:
        tags.append(unreal.Name(ROAD_SPLINE_TAG))
        spline.set_editor_property("component_tags", tags)


def _route_points(route_name):
    if route_name == "A":
        return [
            unreal.Vector(GRID_ORIGIN.x - 3600.0, GRID_ORIGIN.y, GRID_ORIGIN.z),
            unreal.Vector(GRID_ORIGIN.x + 3600.0, GRID_ORIGIN.y, GRID_ORIGIN.z),
        ]
    if route_name == "B":
        return [
            unreal.Vector(GRID_ORIGIN.x + 1600.0, GRID_ORIGIN.y - 3100.0, GRID_ORIGIN.z),
            unreal.Vector(GRID_ORIGIN.x + 1600.0, GRID_ORIGIN.y + 3100.0, GRID_ORIGIN.z),
        ]
    raise ValueError("Unknown route: " + str(route_name))


def _set_route(actor, route_name):
    spline = _road_spline(actor)
    _tag_spline(spline)
    points = _route_points(route_name)
    spline.clear_spline_points(False)
    for point in points:
        spline.add_spline_point(point, unreal.SplineCoordinateSpace.WORLD, False)
    for index in range(spline.get_number_of_spline_points()):
        try:
            spline.set_spline_point_type(index, unreal.SplinePointType.LINEAR, False)
        except Exception:
            pass
    spline.set_closed_loop(False, False)
    spline.update_spline()
    try:
        actor.modify()
        spline.modify()
    except Exception:
        pass
    return {
        "route": route_name,
        "point_count": int(spline.get_number_of_spline_points()),
        "length_cm": round(float(spline.get_spline_length()), 2),
        "points": [[round(p.x, 2), round(p.y, 2), round(p.z, 2)] for p in points],
    }


def _generate(pcg_actor):
    rows = []
    for component in pcg_actor.get_components_by_class(unreal.PCGComponent):
        row = {"component": component.get_name()}
        try:
            component.activate(True)
            component.cleanup(True)
            component.generate(True)
            try:
                component.generate_local(True)
            except Exception as local_exc:
                row["generate_local_error"] = str(local_exc)
            row["generated"] = True
        except Exception as exc:
            row["generated"] = False
            row["error"] = str(exc)
        rows.append(row)
    return rows


def _segments(route_name):
    points = _route_points(route_name)
    segments = []
    for index in range(len(points) - 1):
        a = points[index]
        b = points[index + 1]
        dx = float(b.x - a.x)
        dy = float(b.y - a.y)
        length_sq = dx * dx + dy * dy
        if length_sq > 1.0:
            segments.append((float(a.x), float(a.y), dx, dy, length_sq))
    return segments


def _distance_to_route(x, y, route_name):
    best = float("inf")
    for ax, ay, dx, dy, length_sq in _segments(route_name):
        t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / length_sq))
        px = ax + dx * t
        py = ay + dy * t
        dist_sq = (x - px) * (x - px) + (y - py) * (y - py)
        best = min(best, math.sqrt(dist_sq))
    return best


def _instance_locations(actor):
    locations = []
    components = []
    for component in actor.get_components_by_class(unreal.InstancedStaticMeshComponent):
        try:
            count = int(component.get_instance_count())
        except Exception:
            count = 0
        components.append({"component": component.get_name(), "count": count})
        for index in range(count):
            try:
                transform = component.get_instance_transform(index, True)
                loc = transform.translation
                locations.append((float(loc.x), float(loc.y), float(loc.z)))
            except Exception:
                pass
    return locations, components


def _collect_phase(pcg_actor, route_name):
    locations, components = _instance_locations(pcg_actor)
    near_a = []
    near_b = []
    restored_old_a = []
    for index, (x, y, z) in enumerate(locations):
        dist_a = _distance_to_route(x, y, "A")
        dist_b = _distance_to_route(x, y, "B")
        if dist_a < ROAD_CLEARANCE_CM:
            near_a.append((index, dist_a, x, y, z))
        if dist_b < ROAD_CLEARANCE_CM:
            near_b.append((index, dist_b, x, y, z))
        if dist_a < ROAD_CLEARANCE_CM and dist_b >= ROAD_CLEARANCE_CM * 1.2:
            restored_old_a.append((index, dist_a, dist_b, x, y, z))
    active_near = near_a if route_name == "A" else near_b
    inactive_near = near_b if route_name == "A" else near_a
    return {
        "route": route_name,
        "instance_total": len(locations),
        "components": components,
        "active_route_violation_count": len(active_near),
        "near_route_a_count": len(near_a),
        "near_route_b_count": len(near_b),
        "inactive_route_near_count": len(inactive_near),
        "restored_old_a_count": len(restored_old_a),
        "sample_locations": [
            [round(x, 2), round(y, 2), round(z, 2)]
            for x, y, z in locations[:20]
        ],
        "active_violation_samples": [
            {
                "index": item[0],
                "distance_cm": round(item[1], 2),
                "location": [round(item[2], 2), round(item[3], 2), round(item[4], 2)],
            }
            for item in active_near[:20]
        ],
        "restored_old_a_samples": [
            {
                "index": item[0],
                "distance_a_cm": round(item[1], 2),
                "distance_b_cm": round(item[2], 2),
                "location": [round(item[3], 2), round(item[4], 2), round(item[5], 2)],
            }
            for item in restored_old_a[:20]
        ],
    }


def _dirty_packages():
    rows = []
    try:
        for package in unreal.EditorLoadingAndSavingUtils.get_dirty_content_packages():
            rows.append({"type": "content", "name": package.get_name()})
        for package in unreal.EditorLoadingAndSavingUtils.get_dirty_map_packages():
            rows.append({"type": "map", "name": package.get_name()})
    except Exception:
        pass
    return rows


def _cleanup_fixture_actors():
    return _cleanup_existing_fixture()


def _finish_with_error(state, error):
    cleanup = _cleanup_fixture_actors()
    report = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "pass": False,
        "status": "failed",
        "error": str(error),
        "state": {key: value for key, value in state.items() if key not in {"handle", "graph", "road_actor", "pcg_actor"}},
        "cleanup": cleanup,
        "dirty_packages": _dirty_packages(),
    }
    _write_report(report)
    return report


def _finish_success(state):
    phase_a = state.get("phase_a", {})
    phase_b = state.get("phase_b", {})
    cleanup = _cleanup_fixture_actors()
    result_pass = (
        phase_a.get("instance_total", 0) > 0
        and phase_b.get("instance_total", 0) > 0
        and phase_a.get("active_route_violation_count", 1) == 0
        and phase_b.get("active_route_violation_count", 1) == 0
        and phase_b.get("restored_old_a_count", 0) > 0
    )
    report = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "pass": bool(result_pass),
        "status": "passed" if result_pass else "failed",
        "goal": "PCG graph owns road clear/refill: moving spline clears the new route and refills the old route on regeneration.",
        "graph": state.get("graph_report", {}),
        "clearance_cm": ROAD_CLEARANCE_CM,
        "routes": {
            "A": state.get("route_a", {}),
            "B": state.get("route_b", {}),
        },
        "generation": {
            "A": state.get("generation_a", []),
            "B": state.get("generation_b", []),
        },
        "phase_a": phase_a,
        "phase_b": phase_b,
        "pass_conditions": {
            "phase_a_generated_instances": phase_a.get("instance_total", 0) > 0,
            "phase_b_generated_instances": phase_b.get("instance_total", 0) > 0,
            "phase_a_current_route_clear": phase_a.get("active_route_violation_count", 1) == 0,
            "phase_b_current_route_clear": phase_b.get("active_route_violation_count", 1) == 0,
            "old_route_a_refilled_after_route_b": phase_b.get("restored_old_a_count", 0) > 0,
        },
        "cleanup": cleanup,
        "dirty_packages": _dirty_packages(),
    }
    _write_report(report)
    return report


def start_road_aware_forest_clear_refill_validation():
    previous_state = getattr(unreal, STATE_ATTR, None)
    if previous_state and previous_state.get("handle"):
        try:
            unreal.unregister_slate_post_tick_callback(previous_state["handle"])
        except Exception:
            pass

    state = {
        "started_at": time.time(),
        "handle": None,
        "phase": "setup",
        "cleanup_before": _cleanup_existing_fixture(),
        "world": None,
        "graph_report": {},
        "generation_a": [],
        "generation_b": [],
    }
    try:
        world = unreal.EditorLevelLibrary.get_editor_world()
        if not world:
            raise RuntimeError("No editor world is available.")
        state["world"] = world.get_path_name()
        graph_result = _create_or_update_graph()
        state["graph"] = graph_result["graph"]
        state["graph_report"] = {
            key: value
            for key, value in graph_result.items()
            if key != "graph"
        }
        state["road_actor"] = _ensure_road_actor()
        state["pcg_actor"] = _ensure_pcg_volume(state["graph"])
        state["route_a"] = _set_route(state["road_actor"], "A")
        state["generation_a"] = _generate(state["pcg_actor"])
        state["phase"] = "wait_a"
        state["phase_started_at"] = time.time()
    except Exception as exc:
        return _finish_with_error(state, exc)

    def _tick(_delta_seconds):
        if state.get("phase") == "done":
            return False
        try:
            elapsed = time.time() - float(state.get("phase_started_at") or state["started_at"])
            if elapsed < WAIT_SECONDS:
                return True
            if state["phase"] == "wait_a":
                state["phase_a"] = _collect_phase(state["pcg_actor"], "A")
                state["route_b"] = _set_route(state["road_actor"], "B")
                state["generation_b"] = _generate(state["pcg_actor"])
                state["phase"] = "wait_b"
                state["phase_started_at"] = time.time()
                return True
            if state["phase"] == "wait_b":
                state["phase_b"] = _collect_phase(state["pcg_actor"], "B")
                state["phase"] = "done"
                try:
                    unreal.unregister_slate_post_tick_callback(state["handle"])
                except Exception:
                    pass
                _finish_success(state)
                return False
        except Exception as exc:
            state["phase"] = "done"
            try:
                unreal.unregister_slate_post_tick_callback(state["handle"])
            except Exception:
                pass
            _finish_with_error(state, exc)
            return False
        return True

    state["handle"] = unreal.register_slate_post_tick_callback(_tick)
    setattr(unreal, STATE_ATTR, state)

    scheduled = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "status": "scheduled",
        "wait_seconds_per_phase": WAIT_SECONDS,
        "world": state["world"],
        "graph": GRAPH_OBJECT,
        "road_actor": ROAD_ACTOR_LABEL,
        "pcg_volume_actor": PCG_VOLUME_LABEL,
        "clearance_cm": ROAD_CLEARANCE_CM,
        "cleanup_before": state["cleanup_before"],
        "graph_report": state["graph_report"],
        "generation_a": state["generation_a"],
        "route_a": state["route_a"],
        "report_path": _report_path(),
    }
    print(json.dumps(scheduled, ensure_ascii=False))
    return scheduled


def finalize_road_aware_forest_clear_refill_validation():
    state = getattr(unreal, STATE_ATTR, None)
    if not state:
        path = _report_path()
        exists = os.path.exists(path)
        return {"status": "no_active_state", "report_path": path, "report_exists": exists}
    if state.get("phase") == "done":
        return {"status": "done", "report_path": _report_path(), "report_exists": os.path.exists(_report_path())}
    return {
        "status": "running",
        "phase": state.get("phase"),
        "elapsed_seconds": round(time.time() - float(state.get("started_at") or time.time()), 2),
        "report_path": _report_path(),
    }


if __name__ == "__main__":
    start_road_aware_forest_clear_refill_validation()
