"""Validate grass generation constrained by a closed spline area.

This is a fixture for the required PCG rule:
- open splines, including 2-point splines, are valid for roads, fences, guides,
  borders, masks, gradients, and other linear placement
- closed splines with at least 3 points are area masks; grass/groundcover must
  spawn inside them

The script uses the existing PCG ecosystem candidate Blueprint and a grass graph
so the output is still generated by PCG components, then validates generated ISM
instance positions against the closed polygon.
"""

import json
import math
import os
import time

import unreal


LEVEL_PATH = "/Game/_MCP_Temp/PCG/LVL_Cubeless_PCG_IntentGallery_MCP"
ACTOR_LABEL = globals().get(
    "CUBELESS_CLOSED_GRASS_ACTOR_LABEL",
    "MCP_PCG_ClosedSplineGrassArea_Source",
)
PCG_VOLUME_LABEL = globals().get(
    "CUBELESS_CLOSED_GRASS_PCG_VOLUME_LABEL",
    "MCP_PCG_ClosedSplineGrassArea_PCGVolume",
)
LEGACY_ACTOR_LABELS = {
    "MCP_PCG_ClosedSplineGrassArea_Test",
}
REPORT_NAME = globals().get(
    "CUBELESS_CLOSED_GRASS_REPORT_NAME",
    "CubelessClosedSplineGrassArea_Report.json",
)
WAIT_SECONDS = 8.0
STATE_ATTR = "_cubeless_closed_spline_grass_area_state"
USE_GRASS_MESH_OVERRIDE = bool(globals().get("CUBELESS_CLOSED_GRASS_USE_MESH_OVERRIDE", False))
SOURCE_ACTOR_TAG = "PCGClosedSplineArea"
DYNAMIC_MESH_ATTR = "DynamicMeshPath"
OVERRIDE_TRUE_ATTR = "MeshOverrideTrue"

BP_OBJECT_PATH = (
    "/Game/_MCP_Temp/PCG/Blueprints/"
    "BP_Cubeless_ClosedSplineAreaAuthoring.BP_Cubeless_ClosedSplineAreaAuthoring"
)
BP_CLASS_PATH = BP_OBJECT_PATH + "_C"
GRASS_GRAPH_PATH = (
    "/Game/_MCP_Temp/PCG/Graphs/"
    "PCG_Cubeless_ClosedSplineGrassArea_MCP"
)
GRASS_DEFAULT_MESH = (
    "/Game/DreamscapeSeries/DreamscapeMountains/Meshes/Foliage/Grass/"
    "SM_Grass_Medium01.SM_Grass_Medium01"
)
GRASS_OVERRIDE_TEST_MESH = (
    "/Game/DreamscapeSeries/DreamscapeMountains/Meshes/Foliage/Plants/"
    "SM_Fern_01.SM_Fern_01"
)
GRASS_MATERIAL_PATH = (
    "/Game/Cubeless/PCG/Runtime/Materials/"
    "MI_Cubeless_PCG_GrassMedium_ForestBalanced"
)

LOCAL_POLYGON = [
    unreal.Vector(-2600.0, -1700.0, 0.0),
    unreal.Vector(1300.0, -2450.0, 0.0),
    unreal.Vector(3150.0, -450.0, 0.0),
    unreal.Vector(2150.0, 2250.0, 0.0),
    unreal.Vector(-1500.0, 2450.0, 0.0),
    unreal.Vector(-3100.0, 350.0, 0.0),
]


def _load_level():
    current = unreal.EditorLevelLibrary.get_editor_world()
    current_path = current.get_path_name() if current else ""
    if current_path.startswith(LEVEL_PATH + "."):
        return {"loaded": False, "world_before": current_path}
    unreal.EditorLevelLibrary.load_level(LEVEL_PATH)
    world = unreal.EditorLevelLibrary.get_editor_world()
    return {"loaded": True, "world_before": current_path, "world_after": world.get_path_name()}


def _load_asset(path):
    asset = unreal.EditorAssetLibrary.load_asset(path)
    if not asset:
        asset = unreal.load_object(None, path)
    return asset


def _object_path(obj):
    if not obj:
        return None
    try:
        return obj.get_path_name()
    except Exception:
        return str(obj)


def _blueprint_variable_exists(blueprint, variable_name):
    try:
        cls = unreal.EditorAssetLibrary.load_blueprint_class(BP_OBJECT_PATH)
        if cls:
            cdo = unreal.get_default_object(cls)
            cdo.get_editor_property(variable_name)
            return True
    except Exception:
        pass
    try:
        for desc in blueprint.get_editor_property("new_variables"):
            if str(desc.get_editor_property("var_name")) == variable_name:
                return True
    except Exception:
        pass
    return False


def _set_variable_editable(blueprint, variable_name, value=True):
    try:
        unreal.BlueprintEditorLibrary.set_blueprint_variable_instance_editable(
            blueprint, variable_name, bool(value)
        )
    except Exception:
        pass
    try:
        unreal.BlueprintEditorLibrary.set_blueprint_variable_expose_on_spawn(
            blueprint, variable_name, bool(value)
        )
    except Exception:
        pass


def _ensure_blueprint_grass_override_variables():
    blueprint = _load_asset(BP_OBJECT_PATH)
    if not blueprint:
        raise RuntimeError("Missing validation Blueprint: " + BP_OBJECT_PATH)
    bool_type = unreal.BlueprintEditorLibrary.get_basic_type_by_name("bool")
    mesh_type = unreal.BlueprintEditorLibrary.get_object_reference_type(unreal.StaticMesh.static_class())
    specs = [
        ("UseGrassMeshOverride", bool_type, False),
        ("GrassMeshOverride", mesh_type, GRASS_DEFAULT_MESH),
    ]
    added = []
    for name, pin_type, _default_value in specs:
        if _blueprint_variable_exists(blueprint, name):
            continue
        if not unreal.BlueprintEditorLibrary.add_member_variable(blueprint, name, pin_type):
            raise RuntimeError("Failed to add Blueprint variable: " + name)
        added.append(name)
    for name, _pin_type, _default_value in specs:
        _set_variable_editable(blueprint, name, True)
    blueprint.modify()
    unreal.BlueprintEditorLibrary.compile_blueprint(blueprint)
    cls = unreal.EditorAssetLibrary.load_blueprint_class(BP_OBJECT_PATH)
    if not cls:
        raise RuntimeError("Failed to load validation Blueprint class: " + BP_OBJECT_PATH)
    cdo = unreal.get_default_object(cls)
    cdo.modify()
    cdo.set_editor_property("UseGrassMeshOverride", False)
    cdo.set_editor_property("GrassMeshOverride", _load_asset(GRASS_DEFAULT_MESH))
    unreal.BlueprintEditorLibrary.compile_blueprint(blueprint)
    saved = bool(unreal.EditorAssetLibrary.save_loaded_asset(blueprint))
    return {"added": added, "saved": saved}


def _apply_grass_mesh_override_properties(actor, use_override=None):
    if use_override is None:
        use_override = USE_GRASS_MESH_OVERRIDE
    mesh_path = GRASS_OVERRIDE_TEST_MESH if use_override else GRASS_DEFAULT_MESH
    actor.set_editor_property("UseGrassMeshOverride", bool(use_override))
    actor.set_editor_property("GrassMeshOverride", _load_asset(mesh_path))
    return {
        "use_grass_mesh_override": bool(use_override),
        "grass_mesh_override": mesh_path,
    }


def _make_rotator(pitch=0.0, yaw=0.0, roll=0.0):
    rotator = unreal.Rotator()
    rotator.pitch = float(pitch)
    rotator.yaw = float(yaw)
    rotator.roll = float(roll)
    return rotator


def _find_actor(label):
    for actor in unreal.EditorLevelLibrary.get_all_level_actors():
        if actor.get_actor_label() == label:
            return actor
    return None


def _delete_existing():
    deleted = 0
    for actor in list(unreal.EditorLevelLibrary.get_all_level_actors()):
        if actor.get_actor_label() not in ({ACTOR_LABEL, PCG_VOLUME_LABEL} | LEGACY_ACTOR_LABELS):
            continue
        for component in actor.get_components_by_class(unreal.PCGComponent):
            try:
                component.cleanup(True)
            except Exception:
                pass
        try:
            unreal.EditorLevelLibrary.destroy_actor(actor)
            deleted += 1
        except Exception:
            pass
    return deleted


def _sample_ground_z(world, x, y, fallback_z=0.0):
    start = unreal.Vector(x, y, 50000.0)
    end = unreal.Vector(x, y, -10000.0)
    try:
        hit = unreal.SystemLibrary.line_trace_single(
            world,
            start,
            end,
            unreal.TraceTypeQuery.TRACE_TYPE_QUERY1,
            False,
            [],
            unreal.DrawDebugTrace.NONE,
            True,
        )
        values = hit.to_tuple()
    except Exception:
        return fallback_z, False

    if not values or not bool(values[0]):
        return fallback_z, False
    try:
        actor = values[9]
        actor_name = actor.get_name() if actor else ""
        actor_class = actor.get_class().get_name() if actor else ""
    except Exception:
        actor_name = ""
        actor_class = ""
    if "Landscape" not in actor_name and "Landscape" not in actor_class:
        return fallback_z, False
    try:
        return float(values[4].z), True
    except Exception:
        return fallback_z, False


def _configure_spline(actor):
    splines = actor.get_components_by_class(unreal.SplineComponent)
    if not splines:
        raise RuntimeError("Fixture actor has no SplineComponent.")
    spline = splines[0]
    spline.clear_spline_points(False)
    for point in LOCAL_POLYGON:
        spline.add_spline_point(point, unreal.SplineCoordinateSpace.LOCAL, False)
    for index in range(spline.get_number_of_spline_points()):
        try:
            spline.set_spline_point_type(index, unreal.SplinePointType.LINEAR, False)
        except Exception:
            pass
    spline.set_closed_loop(True, False)
    spline.update_spline()
    try:
        spline.set_editor_property(
            "component_tags",
            [unreal.Name("PCGClosedSplineArea"), unreal.Name("PCGGrassArea")],
        )
    except Exception:
        pass
    return spline


def _world_polygon(actor):
    location = actor.get_actor_location()
    rotation = actor.get_actor_rotation()
    yaw = math.radians(float(rotation.yaw))
    cos_yaw = math.cos(yaw)
    sin_yaw = math.sin(yaw)
    points = []
    for point in LOCAL_POLYGON:
        x = location.x + point.x * cos_yaw - point.y * sin_yaw
        y = location.y + point.x * sin_yaw + point.y * cos_yaw
        points.append((float(x), float(y)))
    return points


def _point_in_polygon(x, y, polygon):
    inside = False
    count = len(polygon)
    j = count - 1
    for i in range(count):
        xi, yi = polygon[i]
        xj, yj = polygon[j]
        crosses = (yi > y) != (yj > y)
        if crosses:
            x_at_y = (xj - xi) * (y - yi) / ((yj - yi) or 1e-9) + xi
            if x < x_at_y:
                inside = not inside
        j = i
    return inside


def _component_tags(component):
    try:
        return [str(tag) for tag in component.get_editor_property("component_tags")]
    except Exception:
        return []


def _set_component_tags(component, tags):
    try:
        component.set_editor_property("component_tags", [unreal.Name(str(tag)) for tag in tags])
    except Exception:
        pass


def _configure_pcg(actor, graph):
    rows = []
    components = list(actor.get_components_by_class(unreal.PCGComponent))
    enabled_names = {"PCG_Style"} if any(c.get_name() == "PCG_Style" for c in components) else set()
    if not enabled_names and components:
        enabled_names.add(components[0].get_name())
    for component in components:
        name = component.get_name()
        enabled = name in enabled_names
        row = {"component": name, "enabled": enabled}
        try:
            component.cleanup(True)
        except Exception as exc:
            row["cleanup_error"] = str(exc)
        try:
            if enabled:
                component.activate(True)
                component.set_graph(graph)
                try:
                    component.set_editor_property("seed", 6112028)
                except Exception:
                    pass
            else:
                component.deactivate()
            row["configured"] = True
        except Exception as exc:
            row["configured"] = False
            row["error"] = str(exc)
        rows.append(row)
    return rows


def _deactivate_source_pcg(actor):
    rows = []
    for component in actor.get_components_by_class(unreal.PCGComponent):
        row = {"component": component.get_name()}
        try:
            component.cleanup(True)
        except Exception as exc:
            row["cleanup_error"] = str(exc)
        try:
            component.deactivate()
            row["deactivated"] = True
        except Exception as exc:
            row["deactivated"] = False
            row["error"] = str(exc)
        rows.append(row)
    return rows


def _generate_enabled_pcg(actor):
    rows = []
    components = list(actor.get_components_by_class(unreal.PCGComponent))
    enabled_names = {"PCG_Style"} if any(c.get_name() == "PCG_Style" for c in components) else set()
    if not enabled_names and components:
        enabled_names.add(components[0].get_name())
    for component in components:
        name = component.get_name()
        enabled = name in enabled_names
        row = {"component": name, "enabled": enabled}
        if not enabled:
            rows.append(row)
            continue
        try:
            component.activate(True)
            component.cleanup(True)
            component.generate(True)
            try:
                component.generate_local(True)
            except Exception as local_exc:
                row["generate_local_error"] = str(local_exc)
            row["generated"] = True
        except Exception as exc:
            row["generated"] = False
            row["error"] = str(exc)
        rows.append(row)
    return rows


def _pin_label(pin):
    try:
        return str(pin.get_editor_property("properties").get_editor_property("label"))
    except Exception:
        try:
            return pin.get_name()
        except Exception:
            return str(pin)


def _add_node(graph, settings_cls, title, x, y):
    created = graph.add_node_of_type(settings_cls.static_class())
    node = created[0] if isinstance(created, tuple) else created
    try:
        node.set_editor_property("node_title", title)
    except Exception:
        try:
            node.node_title = title
        except Exception:
            pass
    try:
        node.set_node_position(int(x), int(y))
    except Exception:
        try:
            node.set_node_position(unreal.Vector2D(float(x), float(y)))
        except Exception:
            pass
    return node


def _add_edge(graph, from_node, to_node, from_pin="Out", to_pin="In"):
    try:
        graph.add_edge(from_node, unreal.Name(from_pin), to_node, unreal.Name(to_pin))
        return {
            "from": from_node.get_name(),
            "from_pin": from_pin,
            "to": to_node.get_name(),
            "to_pin": to_pin,
            "ok": True,
        }
    except Exception as exc:
        return {
            "from": from_node.get_name(),
            "from_pin": from_pin,
            "to": to_node.get_name(),
            "to_pin": to_pin,
            "ok": False,
            "error": str(exc),
        }


def _remove_edge(graph, from_node, to_node, from_pin="Out", to_pin="In"):
    try:
        graph.remove_edge(from_node, unreal.Name(from_pin), to_node, unreal.Name(to_pin))
        return {
            "from": from_node.get_name(),
            "from_pin": from_pin,
            "to": to_node.get_name(),
            "to_pin": to_pin,
            "ok": True,
        }
    except Exception as exc:
        return {
            "from": from_node.get_name(),
            "from_pin": from_pin,
            "to": to_node.get_name(),
            "to_pin": to_pin,
            "ok": False,
            "error": str(exc),
        }


def _selector_import(settings, prop, text):
    selector = settings.get_editor_property(prop)
    selector.import_text("PCGBegin({})PCGEnd".format(text))
    settings.set_editor_property(prop, selector)


def _set_const_value_struct(value_struct, value_type, value):
    value_struct.set_editor_property("type", value_type)
    if value_type == unreal.PCGMetadataTypes.BOOLEAN:
        value_struct.set_editor_property("bool_value", bool(value))
    elif value_type == unreal.PCGMetadataTypes.SOFT_OBJECT_PATH:
        value_struct.set_editor_property("soft_object_path_value", unreal.SoftObjectPath(str(value)))
    elif value_type == unreal.PCGMetadataTypes.STRING:
        value_struct.set_editor_property("string_value", str(value))
    elif value_type == unreal.PCGMetadataTypes.NAME:
        value_struct.set_editor_property("name_value", str(value))
    else:
        value_struct.set_editor_property("double_value", float(value))
        value_struct.set_editor_property("float_value", float(value))
    return value_struct


def _configure_add_attribute(node, output_attr, input_attr, value_type, value):
    settings = node.get_settings()
    settings.set_editor_property("copy_all_attributes", False)
    settings.set_editor_property("copy_all_domains", False)
    _selector_import(settings, "input_source", input_attr)
    _selector_import(settings, "output_target", output_attr)
    value_struct = settings.get_editor_property("attribute_types")
    _set_const_value_struct(value_struct, value_type, value)
    settings.set_editor_property("attribute_types", value_struct)


def _configure_get_actor_property(node, property_name, output_attr):
    settings = node.get_settings()
    actor_selector = settings.get_editor_property("actor_selector")
    actor_selector.set_editor_property("actor_filter", unreal.PCGActorFilter.ALL_WORLD_ACTORS)
    actor_selector.set_editor_property("actor_selection", unreal.PCGActorSelection.BY_TAG)
    actor_selector.set_editor_property("actor_selection_tag", SOURCE_ACTOR_TAG)
    actor_selector.set_editor_property("select_multiple", False)
    actor_selector.set_editor_property("ignore_self_and_children", False)
    settings.set_editor_property("actor_selector", actor_selector)
    settings.set_editor_property("property_name", property_name)
    settings.set_editor_property("always_requery_actors", True)
    settings.set_editor_property("force_object_and_struct_extraction", False)
    settings.set_editor_property("sanitize_output_attribute_name", True)
    _selector_import(settings, "output_attribute_name", output_attr)


def _configure_actor_bool_filter(node, use_property_name):
    settings = node.get_settings()
    settings.set_editor_property("operator", unreal.PCGAttributeFilterOperator.EQUAL)
    settings.set_editor_property("use_constant_threshold", False)
    settings.set_editor_property("use_spatial_query", False)
    _selector_import(settings, "target_attribute", OVERRIDE_TRUE_ATTR)
    _selector_import(settings, "threshold_attribute", use_property_name)
    settings.set_editor_property("warn_on_data_missing_attribute", False)
    settings.set_editor_property("generate_output_data_even_if_empty", True)


def _configure_copy_actor_mesh(node, source_attr, target_attr):
    settings = node.get_settings()
    settings.set_editor_property("copy_all_attributes", False)
    settings.set_editor_property("copy_all_domains", False)
    _selector_import(settings, "input_source", source_attr)
    _selector_import(settings, "output_target", target_attr)


def _configure_weighted_spawner(node, mesh_paths):
    settings = node.get_settings()
    entries = []
    for mesh_path in mesh_paths:
        mesh = _load_asset(mesh_path)
        if not mesh:
            raise RuntimeError("Missing static mesh: " + mesh_path)
        descriptor = unreal.PCGSoftISMComponentDescriptor()
        descriptor.set_editor_property("static_mesh", mesh)
        entry = unreal.PCGMeshSelectorWeightedEntry()
        entry.set_editor_property("descriptor", descriptor)
        entry.set_editor_property("weight", 1)
        entries.append(entry)
    params = settings.get_editor_property("mesh_selector_parameters")
    params.set_editor_property("mesh_entries", entries)


def _configure_by_attribute_spawner(node):
    settings = node.get_settings()
    settings.set_editor_property("allow_descriptor_changes", True)
    settings.set_mesh_selector_type(unreal.PCGMeshSelectorByAttribute.static_class())
    params = settings.get_editor_property("mesh_selector_parameters")
    params.set_editor_property("attribute_name", DYNAMIC_MESH_ATTR)
    params.set_editor_property("use_attribute_material_overrides", False)
    params.set_editor_property("material_override_attributes", [])


def _node_title(node):
    try:
        return str(node.get_editor_property("node_title"))
    except Exception:
        return str(getattr(node, "node_title", ""))


def _node_summary(node):
    try:
        settings_class = node.get_settings().get_class().get_name()
    except Exception:
        settings_class = ""
    return {
        "node": node.get_name(),
        "title": _node_title(node),
        "settings_class": settings_class,
        "input_pins": [{"label": _pin_label(pin), "connected": bool(pin.is_connected())} for pin in getattr(node, "input_pins", [])],
        "output_pins": [{"label": _pin_label(pin), "connected": bool(pin.is_connected())} for pin in getattr(node, "output_pins", [])],
    }


def _is_generated_grass_mesh_override_node(node):
    title = _node_title(node)
    try:
        cls_name = node.get_settings().get_class().get_name()
    except Exception:
        cls_name = ""
    if "Closed Grass Mesh Override" in title:
        return True
    if "GrassMeshOverride" in title or "UseGrassMeshOverride" in title:
        return True
    if cls_name == "PCGStaticMeshSpawnerSettings" and "ByActorMeshOverride" in title:
        return True
    return False


def _remove_generated_grass_mesh_override_nodes(graph):
    removed = []
    for node in list(graph.nodes):
        if not _is_generated_grass_mesh_override_node(node):
            continue
        try:
            removed.append(_node_summary(node))
            graph.remove_node(node)
        except Exception:
            pass
    return removed


def _find_graph_nodes_for_mesh_override(graph):
    sampler = None
    difference = None
    default_spawner = None
    for node in list(graph.nodes):
        try:
            cls_name = node.get_settings().get_class().get_name()
        except Exception:
            cls_name = ""
        title = _node_title(node)
        if cls_name == "PCGSplineSamplerSettings":
            sampler = node
        elif cls_name == "PCGDifferenceSettings":
            difference = node
        elif cls_name == "PCGStaticMeshSpawnerSettings" and "ByActorMeshOverride" not in title:
            default_spawner = node
    upstream = difference or sampler
    if not upstream or not default_spawner:
        raise RuntimeError("Closed grass graph could not find upstream sampler/difference and default spawner.")
    return upstream, default_spawner


def _ensure_closed_grass_graph_mesh_override(graph, direct_by_attribute=False):
    if not graph:
        raise RuntimeError("Missing closed grass graph for mesh override update.")
    removed = _remove_generated_grass_mesh_override_nodes(graph)
    upstream, default_spawner = _find_graph_nodes_for_mesh_override(graph)
    output_node = graph.get_output_node()

    edges = [
        _remove_edge(graph, upstream, default_spawner, "Out", "In"),
        _remove_edge(graph, default_spawner, output_node, "Out", "Out"),
    ]

    try:
        default_spawner.set_editor_property(
            "node_title",
            "Spawn Closed Area Grass Actor Property Direct"
            if direct_by_attribute
            else "Spawn Closed Area Grass Weighted Default",
        )
    except Exception:
        pass
    try:
        default_spawner.set_node_position(1440, 140)
    except Exception:
        pass
    if direct_by_attribute:
        _configure_by_attribute_spawner(default_spawner)
        get_mesh = _add_node(
            graph,
            unreal.PCGGetActorPropertySettings,
            "Closed Grass Mesh Override Get GrassMeshOverride",
            980,
            -260,
        )
        copy_mesh = _add_node(
            graph,
            unreal.PCGCopyAttributesSettings,
            "Closed Grass Mesh Override Copy To DynamicMeshPath",
            1320,
            -80,
        )
        _configure_get_actor_property(get_mesh, "GrassMeshOverride", "GrassMeshOverride")
        _configure_copy_actor_mesh(copy_mesh, "GrassMeshOverride", DYNAMIC_MESH_ATTR)
        edges.extend(
            [
                _add_edge(graph, upstream, copy_mesh, "Out", "Target"),
                _add_edge(graph, get_mesh, copy_mesh, "Out", "Source"),
                _add_edge(graph, copy_mesh, default_spawner, "Out", "In"),
                _add_edge(graph, default_spawner, output_node, "Out", "Out"),
            ]
        )
        try:
            graph.description = (
                "Closed-spline grass area validation graph. StaticMeshSpawner uses "
                "GrassMeshOverride actor property directly after the upstream PCG data path."
            )
        except Exception:
            pass
        saved = bool(unreal.EditorAssetLibrary.save_loaded_asset(graph, False))
        return {
            "graph": graph.get_path_name(),
            "mode": "direct_by_attribute",
            "removed_generated_override_nodes": removed,
            "upstream": _node_summary(upstream),
            "default_spawner": _node_summary(default_spawner),
            "override_attribute": DYNAMIC_MESH_ATTR,
            "actor_property_tag": SOURCE_ACTOR_TAG,
            "default_mesh": GRASS_DEFAULT_MESH,
            "override_test_mesh": GRASS_OVERRIDE_TEST_MESH,
            "edges": edges,
            "edge_errors": [edge for edge in edges if not edge.get("ok")],
            "saved": saved,
        }

    _configure_weighted_spawner(default_spawner, [GRASS_DEFAULT_MESH])

    flag = _add_node(
        graph,
        unreal.PCGAddAttributeSettings,
        "Closed Grass Mesh Override Flag True",
        640,
        0,
    )
    get_use = _add_node(
        graph,
        unreal.PCGGetActorPropertySettings,
        "Closed Grass Mesh Override Get UseGrassMeshOverride",
        640,
        -320,
    )
    split = _add_node(
        graph,
        unreal.PCGAttributeFilteringSettings,
        "Closed Grass Mesh Override Split",
        980,
        0,
    )
    get_mesh = _add_node(
        graph,
        unreal.PCGGetActorPropertySettings,
        "Closed Grass Mesh Override Get GrassMeshOverride",
        1320,
        -320,
    )
    copy_mesh = _add_node(
        graph,
        unreal.PCGCopyAttributesSettings,
        "Closed Grass Mesh Override Copy To DynamicMeshPath",
        1660,
        -120,
    )
    override_spawner = _add_node(
        graph,
        unreal.PCGStaticMeshSpawnerSettings,
        "Closed Grass Mesh Override Spawn ByActorMeshOverride",
        2000,
        -120,
    )
    merge = _add_node(
        graph,
        unreal.PCGMergeSettings,
        "Closed Grass Mesh Override Merge",
        2380,
        0,
    )

    _configure_add_attribute(flag, OVERRIDE_TRUE_ATTR, "@Last", unreal.PCGMetadataTypes.BOOLEAN, True)
    _configure_get_actor_property(get_use, "UseGrassMeshOverride", "UseGrassMeshOverride")
    _configure_actor_bool_filter(split, "UseGrassMeshOverride")
    _configure_get_actor_property(get_mesh, "GrassMeshOverride", "GrassMeshOverride")
    _configure_copy_actor_mesh(copy_mesh, "GrassMeshOverride", DYNAMIC_MESH_ATTR)
    _configure_by_attribute_spawner(override_spawner)

    edges.extend(
        [
            _add_edge(graph, upstream, flag, "Out", "In"),
            _add_edge(graph, flag, split, "Out", "In"),
            _add_edge(graph, get_use, split, "Out", "Filter"),
            _add_edge(graph, split, default_spawner, "OutsideFilter", "In"),
            _add_edge(graph, split, copy_mesh, "InsideFilter", "Target"),
            _add_edge(graph, get_mesh, copy_mesh, "Out", "Source"),
            _add_edge(graph, copy_mesh, override_spawner, "Out", "In"),
            _add_edge(graph, default_spawner, merge, "Out", "In"),
            _add_edge(graph, override_spawner, merge, "Out", "In"),
            _add_edge(graph, merge, output_node, "Out", "Out"),
        ]
    )
    try:
        graph.description = (
            "Closed-spline grass area validation graph. StaticMeshSpawner supports "
            "UseGrassMeshOverride/GrassMeshOverride actor properties and keeps weighted "
            "default output when override is disabled."
        )
    except Exception:
        pass
    saved = bool(unreal.EditorAssetLibrary.save_loaded_asset(graph, False))
    return {
        "graph": graph.get_path_name(),
        "mode": "split_default_or_override",
        "removed_generated_override_nodes": removed,
        "upstream": _node_summary(upstream),
        "default_spawner": _node_summary(default_spawner),
        "override_attribute": DYNAMIC_MESH_ATTR,
        "actor_property_tag": SOURCE_ACTOR_TAG,
        "default_mesh": GRASS_DEFAULT_MESH,
        "override_test_mesh": GRASS_OVERRIDE_TEST_MESH,
        "edges": edges,
        "edge_errors": [edge for edge in edges if not edge.get("ok")],
        "saved": saved,
    }


def _classify(component):
    text = component.get_name().lower()
    try:
        mesh = component.get_editor_property("static_mesh")
        if mesh:
            text += " " + mesh.get_path_name().lower()
    except Exception:
        pass
    if "grass" in text:
        return "grass"
    if any(token in text for token in ["flower", "fern", "leaf", "plant"]):
        return "plant"
    if any(token in text for token in ["tree", "pine", "conifer"]):
        return "tree"
    if any(token in text for token in ["rock", "stone", "boulder"]):
        return "rock"
    return "other"


def _clamp_angle(value, limit=5.0):
    while value > 180.0:
        value -= 360.0
    while value < -180.0:
        value += 360.0
    return max(-limit, min(limit, value))


def _actor_tags(actor):
    try:
        return [str(tag) for tag in actor.tags]
    except Exception:
        return []


def _tagged_as_block(actor, component=None):
    tags = _actor_tags(actor)
    if component is not None:
        tags.extend(_component_tags(component))
    return any("block" in tag.lower() for tag in tags)


def _component_world_bounds(component):
    try:
        origin = component.bounds.origin
        extent = component.bounds.box_extent
        return origin, extent, "component_bounds"
    except Exception:
        pass

    try:
        local_min, local_max = component.get_local_bounds()
    except Exception:
        return None

    corners = [
        unreal.Vector(x, y, z)
        for x in [local_min.x, local_max.x]
        for y in [local_min.y, local_max.y]
        for z in [local_min.z, local_max.z]
    ]
    world_points = []
    try:
        transform = component.get_component_transform()
    except Exception:
        transform = None
    for corner in corners:
        point = None
        if transform is not None:
            try:
                point = transform.transform_position(corner)
            except Exception:
                point = None
        if point is None:
            try:
                owner = component.get_owner()
                location = owner.get_actor_location()
                scale = owner.get_actor_scale3d()
                point = unreal.Vector(
                    location.x + corner.x * scale.x,
                    location.y + corner.y * scale.y,
                    location.z + corner.z * scale.z,
                )
            except Exception:
                continue
        world_points.append(point)
    if not world_points:
        return None
    min_x = min(point.x for point in world_points)
    max_x = max(point.x for point in world_points)
    min_y = min(point.y for point in world_points)
    max_y = max(point.y for point in world_points)
    min_z = min(point.z for point in world_points)
    max_z = max(point.z for point in world_points)
    origin = unreal.Vector((min_x + max_x) * 0.5, (min_y + max_y) * 0.5, (min_z + max_z) * 0.5)
    extent = unreal.Vector((max_x - min_x) * 0.5, (max_y - min_y) * 0.5, (max_z - min_z) * 0.5)
    return origin, extent, "local_bounds"


def _collect_block_bounds():
    bounds = []
    seen = set()
    for actor in unreal.EditorLevelLibrary.get_all_level_actors():
        actor_is_block = _tagged_as_block(actor)
        for component in actor.get_components_by_class(unreal.StaticMeshComponent):
            if not actor_is_block and not _tagged_as_block(actor, component):
                continue
            resolved = _component_world_bounds(component)
            if not resolved:
                continue
            origin, extent, source = resolved
            key = (
                actor.get_path_name(),
                component.get_name(),
                round(float(origin.x), 3),
                round(float(origin.y), 3),
                round(float(origin.z), 3),
                round(float(extent.x), 3),
                round(float(extent.y), 3),
                round(float(extent.z), 3),
            )
            if key in seen:
                continue
            seen.add(key)
            bounds.append(
                {
                    "actor": actor.get_actor_label(),
                    "component": component.get_name(),
                    "origin": [float(origin.x), float(origin.y), float(origin.z)],
                    "extent": [float(extent.x), float(extent.y), float(extent.z)],
                    "bounds_source": source,
                }
            )
    return bounds


def _inside_block(location, block_bounds, margin=120.0):
    for entry in block_bounds or []:
        origin = entry.get("origin") or [0.0, 0.0, 0.0]
        extent = entry.get("extent") or [0.0, 0.0, 0.0]
        if (
            abs(location.x - origin[0]) <= extent[0] + margin
            and abs(location.y - origin[1]) <= extent[1] + margin
        ):
            return True
    return False


def _stabilize_component(component, category, material):
    if category == "grass" and material:
        try:
            component.set_material(0, material)
        except Exception:
            pass
    tags = _component_tags(component)
    for tag in ["PCGClosedSplineAreaGenerated", "PCG_GrassArea"]:
        if tag not in tags:
            tags.append(tag)
    _set_component_tags(component, tags)

    changed = 0
    count = int(component.get_instance_count())
    for index in range(count):
        try:
            transform = component.get_instance_transform(index, False)
            rotator = transform.rotation.rotator()
            pitch = _clamp_angle(rotator.pitch)
            roll = _clamp_angle(rotator.roll)
            if abs(pitch - rotator.pitch) > 0.01 or abs(roll - rotator.roll) > 0.01:
                transform.rotation = _make_rotator(pitch, rotator.yaw, roll).quaternion()
                if component.update_instance_transform(index, transform, False, False, True):
                    changed += 1
        except Exception:
            pass
    try:
        component.mark_render_state_dirty()
    except Exception:
        pass
    return changed


def _validate(source_actor, spline, generated_actor):
    polygon = _world_polygon(source_actor)
    block_bounds = _collect_block_bounds()
    grass_material = unreal.EditorAssetLibrary.load_asset(GRASS_MATERIAL_PATH)
    summary = {
        "spline_closed_loop": bool(spline.is_closed_loop()),
        "spline_point_count": int(spline.get_number_of_spline_points()),
        "polygon": [[round(x, 1), round(y, 1)] for x, y in polygon],
        "block_tagged_component_count": len(block_bounds),
        "components": {},
        "instances": {},
        "inside_count": 0,
        "outside_violation_count": 0,
        "outside_samples": [],
        "block_overlap_violation_count": 0,
        "block_overlap_samples": [],
        "pitch_roll_violation_count_after": 0,
        "pitch_roll_clamped_instances": 0,
        "mesh_rows": [],
        "output_meshes": [],
    }

    generated_owner = generated_actor or source_actor
    positive_meshes = set()
    for component in generated_owner.get_components_by_class(unreal.InstancedStaticMeshComponent):
        category = _classify(component)
        count = int(component.get_instance_count())
        mesh_path = None
        try:
            mesh_path = _object_path(component.get_editor_property("static_mesh"))
        except Exception:
            pass
        if count > 0 and mesh_path:
            positive_meshes.add(mesh_path)
        summary["mesh_rows"].append(
            {
                "component": component.get_name(),
                "category": category,
                "mesh": mesh_path,
                "count": count,
            }
        )
        summary["components"][category] = summary["components"].get(category, 0) + 1
        summary["instances"][category] = summary["instances"].get(category, 0) + count
        summary["pitch_roll_clamped_instances"] += _stabilize_component(
            component, category, grass_material
        )

        for index in range(count):
            try:
                world_transform = component.get_instance_transform(index, True)
                location = world_transform.translation
                local_transform = component.get_instance_transform(index, False)
                rotator = local_transform.rotation.rotator()
            except Exception:
                continue

            if abs(_clamp_angle(rotator.pitch) - rotator.pitch) > 0.01:
                summary["pitch_roll_violation_count_after"] += 1
            if abs(_clamp_angle(rotator.roll) - rotator.roll) > 0.01:
                summary["pitch_roll_violation_count_after"] += 1

            if _point_in_polygon(location.x, location.y, polygon):
                summary["inside_count"] += 1
            else:
                summary["outside_violation_count"] += 1
                if len(summary["outside_samples"]) < 20:
                    summary["outside_samples"].append(
                        {
                            "component": component.get_name(),
                            "category": category,
                            "index": index,
                            "location": [
                                round(location.x, 1),
                                round(location.y, 1),
                                round(location.z, 1),
                            ],
                        }
                    )

            if _inside_block(location, block_bounds):
                summary["block_overlap_violation_count"] += 1
                if len(summary["block_overlap_samples"]) < 20:
                    summary["block_overlap_samples"].append(
                        {
                            "component": component.get_name(),
                            "category": category,
                            "index": index,
                            "location": [
                                round(location.x, 1),
                                round(location.y, 1),
                                round(location.z, 1),
                            ],
                        }
                    )

    summary["generated_instance_total"] = sum(summary["instances"].values())
    summary["output_meshes"] = sorted(positive_meshes)
    try:
        requested_override = bool(source_actor.get_editor_property("UseGrassMeshOverride"))
        actor_property_mesh = _object_path(source_actor.get_editor_property("GrassMeshOverride"))
    except Exception:
        requested_override = USE_GRASS_MESH_OVERRIDE
        actor_property_mesh = None
    summary["mesh_override"] = {
        "requested": requested_override,
        "actor_property_mesh": actor_property_mesh,
        "output_meshes": summary["output_meshes"],
        "actor_property_mesh_override_pass": (
            not requested_override
            or (
                bool(summary["output_meshes"])
                and summary["output_meshes"] == [actor_property_mesh]
            )
        ),
    }
    summary["pass"] = (
        summary["spline_closed_loop"]
        and summary["spline_point_count"] >= 3
        and summary["generated_instance_total"] > 0
        and summary["outside_violation_count"] == 0
        and summary["block_overlap_violation_count"] == 0
        and summary["pitch_roll_violation_count_after"] == 0
        and summary["mesh_override"]["actor_property_mesh_override_pass"]
    )
    return summary


def _write_report(report):
    out_dir = os.path.join(unreal.Paths.project_saved_dir(), "MCP_PCG")
    os.makedirs(out_dir, exist_ok=True)
    report_path = os.path.join(out_dir, REPORT_NAME)
    with open(report_path, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, ensure_ascii=False)
    print(json.dumps({"report": report_path, **report}, ensure_ascii=False))
    return report_path


def _finish(state):
    actor = _find_actor(ACTOR_LABEL)
    if not actor:
        raise RuntimeError("Fixture source actor disappeared: " + ACTOR_LABEL)
    pcg_actor = _find_actor(PCG_VOLUME_LABEL)
    if not pcg_actor:
        raise RuntimeError("Fixture PCGVolume disappeared: " + PCG_VOLUME_LABEL)
    splines = actor.get_components_by_class(unreal.SplineComponent)
    if not splines:
        raise RuntimeError("Fixture actor has no SplineComponent at finish.")
    validation = _validate(actor, splines[0], pcg_actor)
    try:
        unreal.EditorLevelLibrary.save_current_level()
        save_current_level = True
    except Exception as exc:
        save_current_level = "failed: " + str(exc)

    report = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "world": unreal.EditorLevelLibrary.get_editor_world().get_path_name(),
        "fixture_actor": ACTOR_LABEL,
        "pcg_volume_actor": PCG_VOLUME_LABEL,
        "policy": {
            "open_spline": "roads, fences, guides, borders, clear masks, density gradients, and other linear placement; 2-point splines are valid here",
            "closed_spline": "3+ point area masks for grass/groundcover generation",
        },
        "implementation_expectation": {
            "linear_spline_support_must_remain": True,
            "closed_area_spline_requires_dedicated_sampling": True,
            "candidate_bp_reuse_is_only_a_probe": True,
        },
        "level_load": state.get("level_load", {}),
        "deleted_existing": state.get("deleted_existing", 0),
        "blueprint_update": state.get("blueprint_update", {}),
        "graph_update": state.get("graph_update", {}),
        "source_actor_properties": state.get("source_actor_properties", {}),
        "source_pcg_components": state.get("source_pcg_components", []),
        "pcg_components": state.get("pcg_components", []),
        "pcg_generation": state.get("pcg_generation", []),
        "validation": validation,
        "save_current_level": save_current_level,
    }
    report["pass"] = bool(validation.get("pass"))
    return _write_report(report)


def validate_closed_spline_grass_area():
    previous_state = getattr(unreal, STATE_ATTR, None)
    if previous_state and previous_state.get("handle"):
        try:
            unreal.unregister_slate_post_tick_callback(previous_state["handle"])
        except Exception:
            pass

    level_load = _load_level()
    world = unreal.EditorLevelLibrary.get_editor_world()
    deleted_existing = _delete_existing()

    actor_class = unreal.load_object(None, BP_CLASS_PATH)
    if not actor_class:
        raise RuntimeError("Missing actor class: " + BP_CLASS_PATH)
    graph = unreal.load_object(None, GRASS_GRAPH_PATH)
    if not graph:
        raise RuntimeError("Missing grass graph: " + GRASS_GRAPH_PATH)
    blueprint_update = _ensure_blueprint_grass_override_variables()
    graph_update = _ensure_closed_grass_graph_mesh_override(graph)

    origin_x = 23800.0
    origin_y = 25300.0
    origin_z, hit_landscape = _sample_ground_z(world, origin_x, origin_y, 0.0)
    source_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        actor_class,
        unreal.Vector(origin_x, origin_y, origin_z),
        _make_rotator(0.0, -12.0, 0.0),
    )
    if not source_actor:
        raise RuntimeError("Failed to spawn closed spline grass actor.")
    source_actor.set_actor_label(ACTOR_LABEL)
    source_actor_properties = _apply_grass_mesh_override_properties(
        source_actor,
        USE_GRASS_MESH_OVERRIDE,
    )
    try:
        source_actor.set_editor_property(
            "tags",
            [
                unreal.Name("PCGClosedSplineArea"),
                unreal.Name("PCGGrassArea"),
                unreal.Name("MCPValidation"),
            ],
        )
    except Exception:
        pass

    source_pcg_components = _deactivate_source_pcg(source_actor)

    pcg_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.PCGVolume,
        unreal.Vector(origin_x, origin_y, origin_z + 500.0),
        _make_rotator(0.0, 0.0, 0.0),
    )
    if not pcg_actor:
        raise RuntimeError("Failed to spawn closed spline grass PCGVolume.")
    pcg_actor.set_actor_label(PCG_VOLUME_LABEL)
    try:
        pcg_actor.set_actor_scale3d(unreal.Vector(120.0, 120.0, 20.0))
    except Exception:
        pass
    try:
        pcg_actor.set_editor_property(
            "tags",
            [
                unreal.Name("MCPValidation"),
                unreal.Name("PCGClosedSplineAreaVolume"),
            ],
        )
    except Exception:
        pass

    state = {
        "started_at": time.time(),
        "generation_started_at": None,
        "handle": None,
        "completed": False,
        "generated_after_settle": False,
        "level_load": level_load,
        "deleted_existing": deleted_existing,
        "hit_landscape": hit_landscape,
        "pcg_volume_actor": PCG_VOLUME_LABEL,
        "blueprint_update": blueprint_update,
        "graph_update": graph_update,
        "source_actor_properties": source_actor_properties,
        "source_pcg_components": source_pcg_components,
        "pcg_components": [],
        "pcg_generation": [],
    }

    def _tick(_delta_seconds):
        if state["completed"]:
            return False
        elapsed = time.time() - state["started_at"]
        if not state["generated_after_settle"]:
            if elapsed < 0.75:
                return True
            settled_source = _find_actor(ACTOR_LABEL)
            settled_pcg = _find_actor(PCG_VOLUME_LABEL)
            if not settled_source or not settled_pcg:
                state["completed"] = True
                _write_report(
                    {
                        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                        "pass": False,
                        "status": "failed",
                        "error": "settled source or PCGVolume actor missing before generation",
                        "source_found": bool(settled_source),
                        "pcg_volume_found": bool(settled_pcg),
                    }
                )
                return False
            state["source_actor_properties"] = _apply_grass_mesh_override_properties(
                settled_source,
                USE_GRASS_MESH_OVERRIDE,
            )
            _configure_spline(settled_source)
            state["pcg_components"] = _configure_pcg(settled_pcg, graph)
            # The configure pass can trigger PCG component setup side effects;
            # apply the closed spline again after that settle point and before
            # the actual validation generation.
            state["source_actor_properties"] = _apply_grass_mesh_override_properties(
                settled_source,
                USE_GRASS_MESH_OVERRIDE,
            )
            _configure_spline(settled_source)
            state["pcg_generation"] = _generate_enabled_pcg(settled_pcg)
            state["generation_started_at"] = time.time()
            state["generated_after_settle"] = True
            return True

        if time.time() - float(state["generation_started_at"] or state["started_at"]) < WAIT_SECONDS:
            return True
        state["completed"] = True
        try:
            unreal.unregister_slate_post_tick_callback(state["handle"])
        except Exception:
            pass
        try:
            state["report_path"] = _finish(state)
        except Exception as exc:
            _write_report(
                {
                    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                    "pass": False,
                    "status": "failed",
                    "error": str(exc),
                    "level_load": state.get("level_load", {}),
                    "pcg_components": state.get("pcg_components", []),
                }
            )
        return False

    state["handle"] = unreal.register_slate_post_tick_callback(_tick)
    setattr(unreal, STATE_ATTR, state)

    scheduled = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "status": "scheduled",
        "wait_seconds": WAIT_SECONDS,
        "fixture_actor": ACTOR_LABEL,
        "pcg_volume_actor": PCG_VOLUME_LABEL,
        "level_load": level_load,
        "deleted_existing": deleted_existing,
        "hit_landscape": hit_landscape,
        "blueprint_update": blueprint_update,
        "graph_update": graph_update,
        "source_actor_properties": source_actor_properties,
        "pcg_components": [],
        "pcg_generation": [],
        "generation_deferred_until_after_spawn_settle": True,
    }
    print(json.dumps(scheduled, ensure_ascii=False))
    return scheduled


if __name__ == "__main__":
    validate_closed_spline_grass_area()
